apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: crud0307
  generateName: argo-crud-template-
  annotations:
    scenarios.ai.sap.com/description: Crud to S4 HANA
    scenarios.ai.sap.com/name: crud0307
    executables.ai.sap.com/name: crud0307
    executables.ai.sap.com/description: crud0307
    artifacts.ai.sap.com/training-data.kind: dataset
    artifacts.ai.sap.com/model.kind: model
  labels:
    ai.sap.com/version: 0.1.0
    scenarios.ai.sap.com/id: crud0307
spec:
  imagePullSecrets:
    - name: amit-docker-registry-secret
  entrypoint: crud0307
