apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: crud2305
  generateName: argo-crud-template-
  annotations:
    scenarios.ai.sap.com/description: A Meaningful Description
    scenarios.ai.sap.com/name: crud2305
    executables.ai.sap.com/name: crud2305
    executables.ai.sap.com/description: crud2305
    artifacts.ai.sap.com/training-data.kind: '"dataset"'
    artifacts.ai.sap.com/model.kind: '"model"'
  labels:
    ai.sap.com/version: 0.1.0
    scenarios.ai.sap.com/id: crud
spec:
  imagePullSecrets:
    - name: amit-docker-registry-secret
  entrypoint: crud
