apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: crud0507
  generateName: argo-crud-template-
  annotations:
    scenarios.ai.sap.com/description: A Demo to Sotiris
    scenarios.ai.sap.com/name: crud0507
    executables.ai.sap.com/name: crud0507
    executables.ai.sap.com/description: crud0507
    artifacts.ai.sap.com/training-data.kind: dataset
    artifacts.ai.sap.com/model.kind: model
  labels:
    ai.sap.com/version: 0.1.0
    scenarios.ai.sap.com/id: crud
spec:
  imagePullSecrets:
    - name: amit-docker-registry-secret
  entrypoint: crud
